ge-andrew/BarterBuddy

README.md

Need approval to add my name to the README.md

Daniel peace

---

README.md

Final pull request for adding names.

Added name to README using git commands.

---

app/src/main/java/com/example/barterbuddy/Item.java

Created the class for holding all data related to an item. We can add more to it in future tasks as needed, but here is the base version.

Created a java class to hold all data related to an item.

---

app/build.gradle.kts
app/google-services.json
app/src/main/java/com/example/barterbuddy/Item.java
app/src/main/java/com/example/barterbuddy/ItemDetailPage.java
app/src/main/java/com/example/barterbuddy/MainActivity.java
app/src/main/java/com/example/barterbuddy/User.java
build.gradle.kts

I completed Task 8B, which was to populate the ItemDetailPage with data from the Firestore and Cloud Storage databases.
I also did some miscellaneous updates such as converting fields to lowerCamelCase to match the style guide and deleting some unnecessary ID fields in Item.java.
I have reviewed the remaining warnings and most of them don't seem like problems, such as currently-unused views and methods which will likely be important later on.

Task 8B, Item Detail Page

---

app/src/main/java/com/example/barterbuddy/MainActivity.java

- added some missing variables back in

Added temp variables back in

---

app/src/main/java/com/example/barterbuddy/Item.java
app/src/main/java/com/example/barterbuddy/ItemDetailPage.java
app/src/main/java/com/example/barterbuddy/OfferTradePage.java

Package relevant data to next activity in an Intent when clicking "Offer Trade"

Completed Task 8C

---

app/src/main/java/com/example/barterbuddy/ItemDetailPage.java

- changed code in ItemDetailsPage to allow it to work with the latest database setup
- also added some code to get the data from the intent for the email, username and itemId

Fixed develop I think

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/barterbuddy/AddNewItem.java
app/src/main/java/com/example/barterbuddy/DemoUserPicker.java
app/src/main/java/com/example/barterbuddy/ItemDetailPage.java
app/src/main/java/com/example/barterbuddy/MainActivity.java
app/src/main/res/layout/activity_demo_user_picker.xml
app/src/main/res/layout/activity_item_detail_page.xml
app/src/main/res/layout/activity_main.xml

I added a new activity to hold a screen that lets you select a user account for the app. 
I also fixed the image views. They now wrap the images in a more natural way with no gray showing on the sides anymore. (lmk what you think of this part)

Create a demo screen to pick a user

---

.idea/google-java-format.xml
app/src/main/java/com/example/barterbuddy/Item.java
app/src/main/java/com/example/barterbuddy/MainActivity.java
app/src/main/java/com/example/barterbuddy/UpdateItemDocument.java
app/src/main/res/layout/activity_main.xml
build.gradle.kts

Added a Class called "UpdateItemDocument" which currently can set an Item's active status and will automatically set the other items belonging to that user to "inactive" if one goes to active. We can extend this class for other common functionality as well.

Task11A completed

---

app/src/main/java/com/example/barterbuddy/AddNewItem.java
app/src/main/java/com/example/barterbuddy/MainActivity.java
app/src/main/res/layout/activity_main.xml

- Patched small errors in merge conflict resolution.    
- Fixed unused edit text views
- Added code to store user email in database with item
- Made all home screen buttons the same size

Patched the few errors from our merge

---

app/src/main/java/com/example/barterbuddy/AddNewItem.java
app/src/main/java/com/example/barterbuddy/UserItemsPage.java

- modified the intent in UserItemsPage to startActivityForResult. This allows the activity to check if an item was added and refresh if it was.
- added the corresponding code to the AddNewItem page to tell the UserItemsPage page that an item was added.
- This allows for the correct functionality of adding an item and then seeing that newly added item in your item list.
- also found some formatting changes to be made.

Fixed an odd behavior with the add item page and the UserItemsPage

---

app/src/main/res/layout/activity_view_user_items.xml
app/src/main/res/layout/recycler_view_row.xml
app/src/main/res/values-night/themes.xml

- adjusted viewUserItems page to allow shadows to show completely
- added peach color to dark mode

Adjusted UI a bit

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/barterbuddy/ItemsAvailablePage.java
app/src/main/java/com/example/barterbuddy/ItemsToTradeRecyclerAdapter.java
app/src/main/java/com/example/barterbuddy/PublicItemDetailPage.java
app/src/main/java/com/example/barterbuddy/UserItemsPage.java

Updated some variable names, added PublicItemDetailPage to manifest, linted all new files.

Matt recycler fixes

---

app/src/main/java/com/example/barterbuddy/activities/AddNewItemPage.java
app/src/main/java/com/example/barterbuddy/adapters/ItemsToTradeRecyclerAdapter.java
app/src/main/java/com/example/barterbuddy/adapters/UserItemsRecyclerViewAdapter.java

Small refactoring changes from class

---

app/src/main/java/com/example/barterbuddy/DemoUserPicker.java
app/src/main/java/com/example/barterbuddy/activities/CreateAccountPage.java
app/src/main/java/com/example/barterbuddy/activities/LoginPage.java
app/src/main/java/com/example/barterbuddy/activities/UserItemsPage.java
app/src/main/res/layout/activity_demo_user_picker.xml
app/src/main/res/layout/activity_login_page.xml
app/src/main/res/layout/activity_view_user_items.xml
app/src/main/res/menu/profile_menu.xml

- added functionality to allow a user to sign in to Firebase Authentication.
- added logout button to personal items page

Completed Task 3B

---

app/src/main/res/layout/activity_adjust_trade_money.xml
app/src/main/res/values/strings.xml

String resource value fixes during bad merge.

XML fixes for string resource values during bad merge.

---

app/src/main/java/com/example/barterbuddy/activities/AdjustTradeMoneyPage.java

Submits trade to firebase, returns user to public offers.

Sprint 2 Task 7 C

---

app/src/main/java/com/example/barterbuddy/activities/ChatPage.java
app/src/main/java/com/example/barterbuddy/models/Trade.java
app/src/main/java/com/example/barterbuddy/network/UpdateTradeDocument.java
app/src/main/java/com/example/barterbuddy/utils/AuthenticationUtil.java
app/src/main/java/com/example/barterbuddy/utils/FirebaseUtil.java
app/src/main/res/layout/activity_chat_page.xml
app/src/main/res/layout/activity_confirmation_dialog_box.xml
app/src/main/res/values/strings.xml

Must be run with "TestChatPageClass" since no activity in the app calls it yet

Completion of Chat Page Task

---

app/src/main/java/com/example/barterbuddy/activities/AdjustTradeMoneyPage.java

Changed query that put trade in Firebase to put item as Reference type to refer to actual item in firebase, not string

Instead of storing trade's item data as string, stores as Reference

---

app/src/main/java/com/example/barterbuddy/models/Trade.java

Trade class now matches Firebase

Trade patch

---

app/src/main/java/com/example/barterbuddy/activities/AddNewItemPage.java
app/src/main/java/com/example/barterbuddy/activities/PersonalItemsDetailPage.java
app/src/main/java/com/example/barterbuddy/activities/PublicItemsDetailPage.java
app/src/main/java/com/example/barterbuddy/adapters/PublicItemsRecyclerAdapter.java
app/src/main/java/com/example/barterbuddy/models/Item.java
app/src/main/res/layout/activity_add_new_personal_item.xml
app/src/main/res/layout/activity_personal_items_detail_page.xml
app/src/main/res/layout/activity_public_items_detail_page.xml
app/src/main/res/layout/public_items_recycler_card.xml
app/src/main/res/values/strings.xml

- added perceived value to Item.java
- added field for inputting value of item in activity_add_new_personal_item.xml
- added backend code in AddNewItemPage.java to allow for input of value and formatting of input
- changed public_items_recycler_card.xml to show value of item
- changed activity_personal_items_detail_page.xml to show value of item
- changed corresponding backed in PersonalItemsDetailPage.java
- changed activity_public_items_detail_page.xml to show value of item
- changed PublicItemsDetailPage.java to

I accidently did 22A and 22B in the same Branch

---

app/src/main/AndroidManifest.xml
app/src/main/res/values/strings.xml

Fixed issues with strings and mainfest

---

app/src/main/AndroidManifest.xml
app/src/main/java/com/example/barterbuddy/activities/CreateAccountPage.java
app/src/main/java/com/example/barterbuddy/activities/LoginPage.java
app/src/main/java/com/example/barterbuddy/activities/MainActivity.java
app/src/main/java/com/example/barterbuddy/activities/ProfilePage.java
app/src/main/res/drawable/profile_bubbles.xml
app/src/main/res/layout/activity_profile_page.xml
app/src/main/res/menu/profile_menu.xml
app/src/main/res/values/strings.xml

- created UI and backend for profile page with the exception of the backend for the rating bar
- fixed bug with the cursor not staying at the end of the password when show password checkbox was clicked

Sprint 3 extra task 1

---

app/src/main/res/layout/trade_recycler_card.xml

Sprint 3 task 94 b patch1

---

.idea/deploymentTargetDropDown.xml
app/src/main/java/com/example/barterbuddy/activities/MainActivity.java
app/src/main/res/layout/activity_barter_page.xml
app/src/main/res/layout/back_to_bartering_page.xml
app/src/main/res/layout/back_to_chatting_page.xml
app/src/main/res/layout/barter_offer_card_view.xml

- finalized UI and fixed bug with back arrow and rating dialog

---

app/src/main/java/com/example/barterbuddy/adapters/TradeCardRecyclerAdapter.java
app/src/main/res/drawable/baseline_circle_24.xml
app/src/main/res/drawable/baseline_circle_24_green.xml
app/src/main/res/drawable/baseline_circle_24_red.xml
app/src/main/res/drawable/baseline_circle_24_yellow.xml
app/src/main/res/layout/trade_recycler_card.xml

- one last thing

---

app/src/main/res/layout/barter_offer_card_view.xml

- missed something
